<?php

namespace Database\Seeders;

use App\Models\DataKNN;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KNNSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [
            [
                'id' => 1,
                'nama' => 'Alif amirulrahmat',
                'usia_id' => 2,
                'gender' => 'L',
                'tb' => 65.00,
                'bb' => 7.00,
                'lk' => 43.00,
                'motorik_id' => 7,
                'bicara_id' => 10,
                'ketegori' => 'Normal',
                'created_at' => '2025-09-11 03:42:54',
                'updated_at' => '2025-09-11 03:42:54'
            ],
            [
                'id' => 2,
                'nama' => 'Alya reskia Mahendra',
                'usia_id' => 4,
                'gender' => 'P',
                'tb' => 75.00,
                'bb' => 9.00,
                'lk' => 45.00,
                'motorik_id' => 19,
                'bicara_id' => 22,
                'ketegori' => 'Normal',
                'created_at' => '2025-09-11 03:45:41',
                'updated_at' => '2025-09-11 03:45:41'
            ],
            [
                'id' => 3,
                'nama' => 'Al gazali zein',
                'usia_id' => 5,
                'gender' => 'L',
                'tb' => 80.00,
                'bb' => 11.00,
                'lk' => 47.00,
                'motorik_id' => 25,
                'bicara_id' => 28,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 03:47:04',
                'updated_at' => '2025-09-11 03:47:04'
            ],
            [
                'id' => 4,
                'nama' => 'Nurasya ramadhani',
                'usia_id' => 5,
                'gender' => 'P',
                'tb' => 82.00,
                'bb' => 11.80,
                'lk' => 48.00,
                'motorik_id' => 25,
                'bicara_id' => 28,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 03:50:11',
                'updated_at' => '2025-09-11 03:50:11'
            ],
            [
                'id' => 5,
                'nama' => 'Abdul latif',
                'usia_id' => 7,
                'gender' => 'L',
                'tb' => 95.00,
                'bb' => 15.80,
                'lk' => 52.00,
                'motorik_id' => 37,
                'bicara_id' => 40,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 03:51:55',
                'updated_at' => '2025-09-11 03:51:55'
            ],
            [
                'id' => 6,
                'nama' => 'Aqila adelia',
                'usia_id' => 6,
                'gender' => 'P',
                'tb' => 84.00,
                'bb' => 12.00,
                'lk' => 49.00,
                'motorik_id' => 31,
                'bicara_id' => 34,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 03:55:07',
                'updated_at' => '2025-09-11 03:55:07'
            ],
            [
                'id' => 7,
                'nama' => 'Muh syahrul syaputra',
                'usia_id' => 7,
                'gender' => 'L',
                'tb' => 93.00,
                'bb' => 14.00,
                'lk' => 51.00,
                'motorik_id' => 38,
                'bicara_id' => 40,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 03:57:07',
                'updated_at' => '2025-09-11 03:57:07'
            ],
            [
                'id' => 8,
                'nama' => 'Hilman al farizki',
                'usia_id' => 7,
                'gender' => 'L',
                'tb' => 102.00,
                'bb' => 18.00,
                'lk' => 55.00,
                'motorik_id' => 38,
                'bicara_id' => 40,
                'ketegori' => 'Normal',
                'created_at' => '2025-09-11 03:59:03',
                'updated_at' => '2025-09-11 03:59:03'
            ],
            [
                'id' => 9,
                'nama' => 'Nur jannah',
                'usia_id' => 2,
                'gender' => 'P',
                'tb' => 66.00,
                'bb' => 7.20,
                'lk' => 43.00,
                'motorik_id' => 7,
                'bicara_id' => 10,
                'ketegori' => 'Normal',
                'created_at' => '2025-09-11 04:00:35',
                'updated_at' => '2025-09-11 04:00:35'
            ],
            [
                'id' => 10,
                'nama' => 'Ahmad muttaqin',
                'usia_id' => 5,
                'gender' => 'L',
                'tb' => 83.00,
                'bb' => 7.50,
                'lk' => 48.00,
                'motorik_id' => 25,
                'bicara_id' => 28,
                'ketegori' => 'Normal',
                'created_at' => '2025-09-11 04:02:10',
                'updated_at' => '2025-09-11 04:02:10'
            ],
            [
                'id' => 11,
                'nama' => 'Muh Syafiq husain',
                'usia_id' => 5,
                'gender' => 'L',
                'tb' => 76.00,
                'bb' => 6.50,
                'lk' => 45.00,
                'motorik_id' => 27,
                'bicara_id' => 29,
                'ketegori' => 'Risiko Berat',
                'created_at' => '2025-09-11 04:51:15',
                'updated_at' => '2025-09-11 04:51:15'
            ],
            [
                'id' => 12,
                'nama' => 'Sartika',
                'usia_id' => 6,
                'gender' => 'P',
                'tb' => 82.00,
                'bb' => 10.50,
                'lk' => 47.00,
                'motorik_id' => 31,
                'bicara_id' => 34,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 04:52:16',
                'updated_at' => '2025-09-11 04:52:16'
            ],
            [
                'id' => 13,
                'nama' => 'Putri maulia',
                'usia_id' => 6,
                'gender' => 'P',
                'tb' => 85.00,
                'bb' => 12.50,
                'lk' => 48.00,
                'motorik_id' => 32,
                'bicara_id' => 34,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 04:53:21',
                'updated_at' => '2025-09-11 04:53:21'
            ],
            [
                'id' => 14,
                'nama' => 'Afida nur tasbita',
                'usia_id' => 7,
                'gender' => 'P',
                'tb' => 90.00,
                'bb' => 14.50,
                'lk' => 50.00,
                'motorik_id' => 37,
                'bicara_id' => 40,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 04:54:31',
                'updated_at' => '2025-09-11 04:54:31'
            ],
            [
                'id' => 15,
                'nama' => 'Fildan',
                'usia_id' => 6,
                'gender' => 'L',
                'tb' => 87.00,
                'bb' => 12.80,
                'lk' => 45.00,
                'motorik_id' => 31,
                'bicara_id' => 34,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 04:55:29',
                'updated_at' => '2025-09-11 04:55:29'
            ],
            [
                'id' => 16,
                'nama' => 'Iqram',
                'usia_id' => 4,
                'gender' => 'L',
                'tb' => 73.00,
                'bb' => 10.50,
                'lk' => 44.00,
                'motorik_id' => 19,
                'bicara_id' => 22,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 04:56:47',
                'updated_at' => '2025-09-11 04:56:47'
            ],
            [
                'id' => 17,
                'nama' => 'Muh risal',
                'usia_id' => 2,
                'gender' => 'L',
                'tb' => 64.00,
                'bb' => 7.00,
                'lk' => 42.50,
                'motorik_id' => 7,
                'bicara_id' => 10,
                'ketegori' => 'Normal',
                'created_at' => '2025-09-11 04:57:58',
                'updated_at' => '2025-09-11 04:57:58'
            ],
            [
                'id' => 18,
                'nama' => 'Andi Yusuf',
                'usia_id' => 5,
                'gender' => 'L',
                'tb' => 74.00,
                'bb' => 8.90,
                'lk' => 44.40,
                'motorik_id' => 25,
                'bicara_id' => 28,
                'ketegori' => 'Risiko Berat',
                'created_at' => '2025-09-11 04:59:04',
                'updated_at' => '2025-09-11 04:59:04'
            ],
            [
                'id' => 19,
                'nama' => 'Naura azzahra',
                'usia_id' => 4,
                'gender' => 'P',
                'tb' => 75.00,
                'bb' => 8.20,
                'lk' => 46.30,
                'motorik_id' => 19,
                'bicara_id' => 22,
                'ketegori' => 'Normal',
                'created_at' => '2025-09-11 05:00:36',
                'updated_at' => '2025-09-11 05:00:36'
            ],
            [
                'id' => 20,
                'nama' => 'Nurul amelia ramadan',
                'usia_id' => 7,
                'gender' => 'P',
                'tb' => 76.00,
                'bb' => 8.00,
                'lk' => 45.10,
                'motorik_id' => 38,
                'bicara_id' => 42,
                'ketegori' => 'Risiko Berat',
                'created_at' => '2025-09-11 05:01:46',
                'updated_at' => '2025-09-11 05:01:46'
            ],
            [
                'id' => 21,
                'nama' => 'Muh ismail ramadan',
                'usia_id' => 5,
                'gender' => 'L',
                'tb' => 76.00,
                'bb' => 7.00,
                'lk' => 44.60,
                'motorik_id' => 25,
                'bicara_id' => 28,
                'ketegori' => 'Risiko Berat',
                'created_at' => '2025-09-11 16:35:33',
                'updated_at' => '2025-09-11 16:35:33'
            ],
            [
                'id' => 22,
                'nama' => 'Ahmad tri wahyudi',
                'usia_id' => 4,
                'gender' => 'L',
                'tb' => 77.50,
                'bb' => 9.10,
                'lk' => 47.80,
                'motorik_id' => 19,
                'bicara_id' => 22,
                'ketegori' => 'Normal',
                'created_at' => '2025-09-11 16:37:03',
                'updated_at' => '2025-09-11 16:37:03'
            ],
            [
                'id' => 23,
                'nama' => 'Manessa Andia putri',
                'usia_id' => 4,
                'gender' => 'P',
                'tb' => 72.50,
                'bb' => 7.40,
                'lk' => 45.20,
                'motorik_id' => 19,
                'bicara_id' => 22,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 16:38:19',
                'updated_at' => '2025-09-11 16:38:19'
            ],
            [
                'id' => 24,
                'nama' => 'Alisa',
                'usia_id' => 6,
                'gender' => 'P',
                'tb' => 7.30,
                'bb' => 7.70,
                'lk' => 45.30,
                'motorik_id' => 32,
                'bicara_id' => 36,
                'ketegori' => 'Risiko Berat',
                'created_at' => '2025-09-11 16:40:18',
                'updated_at' => '2025-09-11 16:40:18'
            ],
            [
                'id' => 25,
                'nama' => 'Hanif hafidzan',
                'usia_id' => 4,
                'gender' => 'L',
                'tb' => 69.00,
                'bb' => 7.90,
                'lk' => 44.50,
                'motorik_id' => 19,
                'bicara_id' => 23,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 16:41:56',
                'updated_at' => '2025-09-11 16:41:56'
            ],
            [
                'id' => 26,
                'nama' => 'Aliya khaliza',
                'usia_id' => 5,
                'gender' => 'P',
                'tb' => 68.50,
                'bb' => 7.40,
                'lk' => 47.10,
                'motorik_id' => 25,
                'bicara_id' => 28,
                'ketegori' => 'Risiko Berat',
                'created_at' => '2025-09-11 16:43:44',
                'updated_at' => '2025-09-11 16:43:44'
            ],
            [
                'id' => 27,
                'nama' => 'Muh fajar',
                'usia_id' => 7,
                'gender' => 'L',
                'tb' => 75.00,
                'bb' => 9.00,
                'lk' => 46.70,
                'motorik_id' => 38,
                'bicara_id' => 40,
                'ketegori' => 'Risiko Berat',
                'created_at' => '2025-09-11 16:45:32',
                'updated_at' => '2025-09-11 16:45:32'
            ],
            [
                'id' => 28,
                'nama' => 'Firmansyah',
                'usia_id' => 4,
                'gender' => 'L',
                'tb' => 71.50,
                'bb' => 8.00,
                'lk' => 44.90,
                'motorik_id' => 20,
                'bicara_id' => 23,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 16:46:55',
                'updated_at' => '2025-09-11 16:46:55'
            ],
            [
                'id' => 29,
                'nama' => 'Nova aulia ganindra',
                'usia_id' => 7,
                'gender' => 'P',
                'tb' => 87.00,
                'bb' => 11.30,
                'lk' => 45.40,
                'motorik_id' => 37,
                'bicara_id' => 40,
                'ketegori' => 'Risiko Berat',
                'created_at' => '2025-09-11 16:48:06',
                'updated_at' => '2025-09-11 16:48:06'
            ],
            [
                'id' => 30,
                'nama' => 'Khayra amanda',
                'usia_id' => 7,
                'gender' => 'P',
                'tb' => 97.00,
                'bb' => 16.70,
                'lk' => 52.00,
                'motorik_id' => 37,
                'bicara_id' => 40,
                'ketegori' => 'Risiko Sedang',
                'created_at' => '2025-09-11 16:49:54',
                'updated_at' => '2025-09-11 16:49:54'
            ],
            [
                'id' => 32,
                'nama' => 'alya reskia mahenda',
                'usia_id' => 2,
                'gender' => 'P',
                'tb' => 75.00,
                'bb' => 9.00,
                'lk' => 45.00,
                'motorik_id' => 7,
                'bicara_id' => 10,
                'ketegori' => 'Normal',
                'created_at' => '2025-09-15 18:11:19',
                'updated_at' => '2025-09-15 18:11:19'
            ]
        ];

        DataKNN::insert($data);
    }
}
