<?php

namespace Database\Seeders;

use App\Models\Rekomendasi;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RekomendasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rekomendasi = [
            [
                'usia_id' => 1,
                'indikator_id' => 1,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Pastikan posisi tidur bayi bergantian (telentang dan tengkurap saat diawasi) untuk mencegah kepala peyang.',
                'rekomendasi2' => 'Berikan stimulasi sensorik dengan mengelus kepala bayi secara lembut.',
                'rekomendasi3' => 'Pantau pertumbuhan kepala secara berkala dengan mengukur lingkar kepala setiap bulan.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 2,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Berikan ASI eksklusif sesuai kebutuhan bayi (8-12 kali sehari).',
                'rekomendasi2' => 'Pastikan ibu mengonsumsi makanan bergizi untuk mendukung kualitas ASI.',
                'rekomendasi3' => 'Pantau kenaikan berat badan setiap minggu.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 3,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Berikan stimulasi gerak aktif seperti menggerakkan kaki dan tangan bayi.',
                'rekomendasi2' => 'Pastikan bayi mendapat cukup sinar matahari pagi untuk vitamin D.',
                'rekomendasi3' => 'Hindari penggunaan gendongan yang terlalu ketat.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 4,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Letakkan mainan berwarna cerah di dekat bayi untuk merangsang penglihatan dan gerakan.',
                'rekomendasi2' => 'Latih refleks menggenggam dengan memberikan jari atau benda kecil untuk dipegang.',
                'rekomendasi3' => 'Ajak bayi berbicara dan tersenyum untuk stimulasi sensorik.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 5,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Ajak bayi berbicara dengan suara lembut dan ekspresif.',
                'rekomendasi2' => 'Berikan respons setiap kali bayi mengeluarkan suara.',
                'rekomendasi3' => 'Mainkan musik atau lagu anak-anak untuk stimulasi pendengaran.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 1,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Konsultasikan dengan dokter anak untuk evaluasi lebih lanjut.',
                'rekomendasi2' => 'Berikan nutrisi yang cukup melalui ASI eksklusif atau susu formula yang direkomendasikan dokter.',
                'rekomendasi3' => 'Hindari tekanan berlebihan pada kepala bayi, seperti penggunaan bantal keras.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 2,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Tingkatkan frekuensi menyusui atau tambahkan susu formula jika diperlukan.',
                'rekomendasi2' => 'Konsultasikan dengan dokter untuk memastikan tidak ada masalah pencernaan.',
                'rekomendasi3' => 'Berikan sentuhan kulit-ke-kulit (skin-to-skin) untuk meningkatkan kenyamanan dan penyerapan nutrisi.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 3,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Periksa asupan nutrisi dan pastikan tidak ada intoleransi laktosa.',
                'rekomendasi2' => 'Lakukan pemantauan tinggi badan setiap bulan.',
                'rekomendasi3' => 'Berikan pijatan lembut untuk merangsang pertumbuhan tulang.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 4,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Lakukan tummy time (tengkurap) 2-3 kali sehari selama 3-5 menit.',
                'rekomendasi2' => 'Gunakan bantal kecil untuk menyangga dada bayi saat tengkurap.',
                'rekomendasi3' => 'Konsultasikan dengan fisioterapis jika perkembangan motorik lambat.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 5,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Perbanyak interaksi verbal dengan bayi.',
                'rekomendasi2' => 'Gunakan mainan yang mengeluarkan suara untuk merangsang respons.',
                'rekomendasi3' => 'Pantau perkembangan pendengaran jika bayi tidak merespons suara.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 1,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Segera bawa ke dokter spesialis anak untuk pemeriksaan medis mendalam.',
                'rekomendasi2' => 'Pastikan asupan nutrisi optimal dengan panduan dokter.',
                'rekomendasi3' => 'Hindari paparan zat berbahaya atau infeksi yang dapat mengganggu pertumbuhan otak.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 2,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Segera cari bantuan medis untuk evaluasi penyebab berat badan rendah.',
                'rekomendasi2' => 'Pertimbangkan suplementasi nutrisi khusus atas rekomendasi dokter.',
                'rekomendasi3' => 'Hindari paparan lingkungan yang tidak higienis untuk mencegah infeksi.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 3,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Segera konsultasikan ke dokter anak untuk pemeriksaan hormon dan genetik.',
                'rekomendasi2' => 'Berikan nutrisi tinggi protein dan kalori sesuai anjuran dokter.',
                'rekomendasi3' => 'Hindari stres pada ibu dan bayi, karena dapat memengaruhi pertumbuhan.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 4,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Segera periksa ke dokter untuk mengevaluasi tonus otot dan saraf.',
                'rekomendasi2' => 'Berikan stimulasi intensif dengan bantuan profesional.',
                'rekomendasi3' => 'Hindari posisi yang membatasi gerakan bayi.',
            ],
            [
                'usia_id' => 1,
                'indikator_id' => 5,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Periksa pendengaran bayi untuk menyingkirkan gangguan.',
                'rekomendasi2' => 'Konsultasikan dengan terapis wicara anak.',
                'rekomendasi3' => 'Berikan stimulasi multisensorik (visual, sentuhan, suara).',
            ],

            [
                'usia_id' => 2,
                'indikator_id' => 1,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Lanjutkan stimulasi sensorik dengan mainan bertekstur.',
                'rekomendasi2' => 'Hindari tekanan berlebihan pada kepala saat tidur (gunakan bantal datar).',
                'rekomendasi3' => 'Pantau pertumbuhan kepala setiap bulan.',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 2,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Perkenalkan MPASI tekstur halus (bubur susu/puree) jika bayi menunjukkan tanda siap.',
                'rekomendasi2' => 'Pertahankan frekuensi menyusui 6-8 kali sehari.',
                'rekomendasi3' => 'Pantau kenaikan berat badan per minggu (minimal 150-200 gram).',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 3,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Latih bayi dalam posisi duduk dengan penyangga untuk memperkuat otot punggung.',
                'rekomendasi2' => 'Berikan mainan yang mendorong gerakan meraih dan menggapai.',
                'rekomendasi3' => 'Pastikan durasi tidur cukup (14-15 jam/hari).',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 4,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Letakkan mainan di samping bayi untuk mendorong berguling.',
                'rekomendasi2' => 'Latih posisi duduk dengan bantuan bantal penyangga.',
                'rekomendasi3' => 'Berikan teether untuk melatih koordinasi tangan-mulut.',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 5,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Ajak bayi bercakap-cakap dengan meniru ocehannya.',
                'rekomendasi2' => 'Bacakan buku dengan gambar warna-warni.',
                'rekomendasi3' => 'Gunakan mainan berbunyi untuk melatih respons pendengaran.',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 1,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Konsultasi dokter untuk mengevaluasi perkembangan otak.',
                'rekomendasi2' => 'Berikan nutrisi tambahan seperti ASI atau susu formula yang diperkaya zat besi.',
                'rekomendasi3' => 'Stimulasi dengan permainan yang merangsang koordinasi mata-tangan.',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 2,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Tingkatkan porsi MPASI dengan tambahan kalori (misal: minyak zaitun).',
                'rekomendasi2' => 'Pastikan bayi tidak mengalami infeksi berulang (diare/ISPA).',
                'rekomendasi3' => 'Konsultasikan kebutuhan suplementasi zinc/vitamin A.',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 3,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Fokus pada asupan kalsium dan vitamin D (sinar matahari pagi, MPASI fortifikasi).',
                'rekomendasi2' => 'Stimulasi motorik dengan permainan "tummy time" lebih intensif.',
                'rekomendasi3' => 'Pantau pertumbuhan tulang dengan pemeriksaan rutin.',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 4,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Latih duduk dengan bantuan tangan orang tua secara bertahap.',
                'rekomendasi2' => 'Gunakan mainan yang mengeluarkan suara untuk menarik perhatian.',
                'rekomendasi3' => 'Hindari terlalu lama di baby bouncer/kursi bayi.',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 5,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Perbanyak kontak mata saat berbicara dengan bayi.',
                'rekomendasi2' => 'Ulangi kata-kata sederhana seperti "mama", "papa".',
                'rekomendasi3' => 'Kurangi paparan gadget atau TV.',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 1,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan neurologis untuk mendeteksi kelainan bawaan.',
                'rekomendasi2' => 'Berikan makanan pendamping ASI (MPASI) dini jika direkomendasikan dokter.',
                'rekomendasi3' => 'Hindari paparan toksin (asap rokok, polusi).',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 2,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Segera evaluasi penyebab kegagalan tumbuh (misal: alergi, kelainan metabolik).',
                'rekomendasi2' => 'Berikan MPASI tinggi protein dan energi sesuai anjuran dokter.',
                'rekomendasi3' => 'Hindari pemberian makanan rendah nutrisi (seperti teh/air tajin).',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 3,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan hormon pertumbuhan dan tiroid.',
                'rekomendasi2' => 'Berikan susu formula khusus untuk bayi dengan berat badan rendah.',
                'rekomendasi3' => 'Hindari gendongan yang menghambat gerak aktif.',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 4,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Terapi fisik dengan fisioterapis untuk memperkuat otot.',
                'rekomendasi2' => 'Stimulasi sentuhan dengan pijatan lembut setiap hari.',
                'rekomendasi3' => 'Konsultasi dokter untuk menyingkirkan cerebral palsy.',
            ],
            [
                'usia_id' => 2,
                'indikator_id' => 5,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan pendengaran (tes OAE/ABR).',
                'rekomendasi2' => 'Gunakan gerakan tangan dan ekspresi wajah saat berkomunikasi.',
                'rekomendasi3' => 'Konsultasi terapis wicara anak.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 1,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Berikan mainan dengan berbagai tekstur (lembut, kasar) untuk merangsang perkembangan otak.',
                'rekomendasi2' => 'Pastikan kepala bayi tidak selalu dalam posisi yang sama untuk menghindari kepala peyang.',
                'rekomendasi3' => 'Ukur lingkar kepala setiap bulan dan catat perkembangannya.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 2,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Perkenalkan tekstur lebih kasar (nasi tim, bubur kental) dan finger food (potongan buah lunak seperti pisang).',
                'rekomendasi2' => 'Berikan MPASI 2-3 kali sehari dengan camilan sehat (biskuit bayi, yoghurt).',
                'rekomendasi3' => 'Timbang berat badan setiap 2 minggu untuk memastikan kenaikan stabil.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 3,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Dorong bayi untuk merangkak dan menjelajah lingkungan aman.',
                'rekomendasi2' => 'Berikan makanan kaya kalsium (keju, yoghurt) dan vitamin D (sinar matahari pagi).',
                'rekomendasi3' => 'Pastikan bayi tidur 12-14 jam/hari (termasuk tidur siang).',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 4,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Letakkan mainan di depan bayi untuk mendorong merangkak.',
                'rekomendasi2' => 'Berikan mainan stackable (cangkir susun) atau bola kecil.',
                'rekomendasi3' => 'Bantu bayi berpegangan pada meja rendah untuk latihan berdiri.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 5,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Gunakan kata-kata sederhana dan ekspresif ("Ini bola! B-O-L-A").',
                'rekomendasi2' => 'Pilih buku dengan gambar besar dan suara (contoh: "Apa suara kucing?").',
                'rekomendasi3' => 'Beri respons antusias saat bayi mengeluarkan suara.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 1,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Berikan makanan tinggi DHA (seperti ikan salmon, kuning telur) untuk mendukung perkembangan otak.',
                'rekomendasi2' => 'Konsultasikan ke dokter anak untuk memastikan tidak ada gangguan neurologis.',
                'rekomendasi3' => 'Gunakan mainan yang mengeluarkan suara untuk melatih respons pendengaran dan koordinasi.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 2,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Campurkan minyak zaitun atau santan encer ke dalam MPASI untuk meningkatkan energi.',
                'rekomendasi2' => 'Berikan sumber protein mudah dicerna (telur, tahu, daging cincang halus).',
                'rekomendasi3' => 'Jaga kebersihan makanan dan lingkungan untuk menghindari diare/ISPA.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 3,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Lakukan "tummy time" lebih lama untuk memperkuat otot punggung dan leher.',
                'rekomendasi2' => 'Jika diperlukan, berikan vitamin D atas rekomendasi dokter.',
                'rekomendasi3' => 'Gunakan mainan dorong untuk mendorong bayi bergerak aktif.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 4,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Gunakan bantal atau kursi bayi untuk stabilitas.',
                'rekomendasi2' => 'Letakkan mainan favorit sedikit di luar jangkauan.',
                'rekomendasi3' => 'Alat ini bisa menghambat perkembangan motorik alami.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 5,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Kurangi gadget, ganti dengan permainan cilukba atau lagu anak.',
                'rekomendasi2' => 'Tekankan kata seperti "mama", "papa", "makan".',
                'rekomendasi3' => 'Kombinasikan kata dengan gerakan (misal: melambai sambil bilang "dadah").',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 1,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Dokter mungkin merekomendasikan USG kepala atau MRI untuk mengevaluasi struktur otak.',
                'rekomendasi2' => 'Fokus pada makanan tinggi protein, zat besi, dan omega-3 (daging tumbuk, hati ayam, alpukat).',
                'rekomendasi3' => 'Jauhi paparan asap rokok, polusi, atau infeksi yang dapat memperburuk pertumbuhan otak.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 2,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Dokter mungkin meresepkan susu formula tinggi kalori atau suplemen nutrisi.',
                'rekomendasi2' => 'Prioritaskan alpukat, kacang merah tumbuk, atau daging blender.',
                'rekomendasi3' => 'Cari tahu penyebab kegagalan tumbuh (misal: alergi, kelainan metabolik).',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 3,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Evaluasi kadar hormon pertumbuhan dan tiroid.',
                'rekomendasi2' => 'Fisioterapis dapat membantu latihan untuk memperbaiki postur tubuh.',
                'rekomendasi3' => 'Tambahkan susu fortifikasi atau MPASI dengan ekstra kalori/protein.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 4,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Fisioterapis akan merancang latihan untuk memperkuat otot inti.',
                'rekomendasi2' => 'Pijat lembut setiap hari untuk meningkatkan tonus otot.',
                'rekomendasi3' => 'Periksa apakah ada cerebral palsy atau gangguan saraf lainnya.',
            ],
            [
                'usia_id' => 3,
                'indikator_id' => 5,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pastikan tidak ada gangguan pendengaran (OAE/ABR).',
                'rekomendasi2' => 'Konsultasi dini dengan terapis untuk stimulasi intensif.',
                'rekomendasi3' => 'Gunakan ekspresi wajah dan bahasa isyarat sederhana.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 1,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Stimulasi dengan permainan menyusun balok untuk melatih koordinasi tangan-mata.',
                'rekomendasi2' => 'Hindari penggunaan headband atau topi yang terlalu ketat.',
                'rekomendasi3' => 'Pantau pertumbuhan kepala setiap 2 bulan.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 2,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Berikan MPASI dengan tekstur lebih padat (nasi lembek, sayur cincang).',
                'rekomendasi2' => 'Perkenalkan sumber protein baru (daging ayam, tahu, tempe).',
                'rekomendasi3' => 'Pantau berat badan setiap bulan untuk memastikan kenaikan stabil.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 3,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Latih bayi untuk berdiri dengan berpegangan pada perabotan.',
                'rekomendasi2' => 'Berikan mainan dorong untuk melatih keseimbangan.',
                'rekomendasi3' => 'Pastikan durasi tidur malam 11-12 jam dan tidur siang 2-3 jam.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 4,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Latih berdiri tanpa bantuan selama beberapa detik.',
                'rekomendasi2' => 'Buat rute merangkak dengan rintangan sederhana (bantal, mainan).',
                'rekomendasi3' => 'Berikan mainan yang mendorong gerakan aktif, seperti bola kecil.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 5,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Ajak bayi berbicara dengan kalimat pendek dan jelas.',
                'rekomendasi2' => 'Bacakan buku cerita dengan gambar dan suara menarik.',
                'rekomendasi3' => 'Ulangi kata-kata yang diucapkan bayi untuk memperkaya kosakata.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 1,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Konsultasikan dengan dokter untuk mengevaluasi perkembangan otak.',
                'rekomendasi2' => 'Berikan makanan tinggi omega-3 (ikan, telur, alpukat).',
                'rekomendasi3' => 'Stimulasi dengan aktivitas yang melibatkan kedua tangan, seperti memindahkan benda kecil.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 2,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Tingkatkan frekuensi makan menjadi 3-4 kali sehari dengan camilan sehat.',
                'rekomendasi2' => 'Tambahkan lemak sehat (minyak kelapa, mentega) ke dalam makanan.',
                'rekomendasi3' => 'Pastikan bayi tidak mengalami infeksi berulang (seperti diare atau cacingan).',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 3,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Fokus pada asupan kalsium (susu, keju, yoghurt) dan vitamin D.',
                'rekomendasi2' => 'Ajak bayi bermain di luar rumah untuk mendapatkan sinar matahari pagi.',
                'rekomendasi3' => 'Pantau pertumbuhan tulang dengan pengukuran rutin.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 4,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Latih keseimbangan dengan memegang kedua tangan bayi saat berdiri.',
                'rekomendasi2' => 'Gunakan mainan yang menarik perhatian untuk mendorong langkah pertama.',
                'rekomendasi3' => 'Hindari penggunaan baby walker yang dapat menghambat perkembangan alami.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 5,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Perbanyak interaksi verbal dengan menunjuk benda dan menyebutkan namanya.',
                'rekomendasi2' => 'Gunakan lagu anak-anak dengan lirik sederhana.',
                'rekomendasi3' => 'Hindari penggunaan gadget atau TV sebagai pengganti interaksi langsung.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 1,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan neurologis dan pencitraan (MRI/CT scan) jika diperlukan.',
                'rekomendasi2' => 'Pastikan asupan nutrisi optimal dengan panduan dokter gizi.',
                'rekomendasi3' => 'Hindari paparan lingkungan yang tidak aman (bahan kimia, infeksi).',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 2,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Segera konsultasikan dengan dokter anak untuk evaluasi medis menyeluruh.',
                'rekomendasi2' => 'Berikan makanan tinggi kalori dan protein (daging cincang, kacang-kacangan tumbuk).',
                'rekomendasi3' => 'Hindari pemberian makanan rendah nutrisi seperti jus kemasan.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 3,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan hormon pertumbuhan dan kondisi tulang.',
                'rekomendasi2' => 'Berikan susu formula khusus untuk anak dengan gangguan pertumbuhan.',
                'rekomendasi3' => 'Hindari aktivitas yang membebani tulang secara berlebihan.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 4,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Terapi fisik dengan fisioterapis untuk memperkuat otot kaki dan punggung.',
                'rekomendasi2' => 'Stimulasi dengan pijatan lembut pada kaki dan punggung.',
                'rekomendasi3' => 'Konsultasi dokter untuk menyingkirkan gangguan neurologis.',
            ],
            [
                'usia_id' => 4,
                'indikator_id' => 5,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan pendengaran dan perkembangan saraf.',
                'rekomendasi2' => 'Konsultasi dengan terapis wicara untuk stimulasi intensif.',
                'rekomendasi3' => 'Gunakan bahasa isyarat sederhana (misal: melambai, tepuk tangan) untuk komunikasi.',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 1,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Ajak bayi bermain dengan mainan yang merangsang koordinasi tangan-mata.',
                'rekomendasi2' => 'Pastikan posisi tidur bayi bergantian untuk mencegah kepala peyang.',
                'rekomendasi3' => 'Pantau pertumbuhan kepala setiap 2 bulan.',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 2,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Perkenalkan MPASI dengan tekstur lebih kasar (nasi tim, sayur cincang).',
                'rekomendasi2' => 'Berikan makanan padat 3 kali sehari dengan camilan sehat di antara waktu makan.',
                'rekomendasi3' => 'Pantau kenaikan berat badan setiap bulan.',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 3,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Latih bayi untuk berdiri dengan berpegangan pada perabotan.',
                'rekomendasi2' => 'Berikan mainan dorong untuk melatih keseimbangan.',
                'rekomendasi3' => 'Pastikan durasi tidur malam 11-12 jam dan tidur siang 2-3 jam.',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 4,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Latih berdiri tanpa bantuan selama beberapa detik.',
                'rekomendasi2' => 'Buat rute merangkak dengan rintangan sederhana (bantal, mainan).',
                'rekomendasi3' => 'Berikan mainan yang mendorong gerakan aktif, seperti bola kecil.',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 5,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Ajak bayi berbicara dengan kalimat pendek dan jelas.',
                'rekomendasi2' => 'Bacakan buku cerita dengan gambar dan suara menarik.',
                'rekomendasi3' => 'Ulangi kata-kata yang diucapkan bayi untuk memperkaya kosakata.',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 1,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Konsultasikan dengan dokter untuk mengevaluasi perkembangan otak.',
                'rekomendasi2' => 'Berikan makanan tinggi omega-3 (ikan, telur, alpukat).',
                'rekomendasi3' => 'Stimulasi dengan aktivitas yang melibatkan kedua tangan, seperti memindahkan benda kecil.',
            ],
            [                'usia_id' => 5,
                'indikator_id' => 2,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Tingkatkan frekuensi makan menjadi 3-4 kali sehari dengan camilan sehat.',
                'rekomendasi2' => 'Tambahkan lemak sehat (minyak kelapa, mentega) ke dalam makanan.',
                'rekomendasi3' => 'Pastikan bayi tidak mengalami infeksi berulang (seperti diare atau cacingan).',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 3,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Fokus pada asupan kalsium (susu, keju, yoghurt) dan vitamin D.',
                'rekomendasi2' => 'Ajak bayi bermain di luar rumah untuk mendapatkan sinar matahari pagi.',
                'rekomendasi3' => 'Pantau pertumbuhan tulang dengan pengukuran rutin.',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 4,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Latih keseimbangan dengan memegang kedua tangan bayi saat berdiri.',
                'rekomendasi2' => 'Gunakan mainan yang menarik perhatian untuk mendorong langkah pertama.',
                'rekomendasi3' => 'Hindari penggunaan baby walker yang dapat menghambat perkembangan alami.',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 5,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Perbanyak interaksi verbal dengan menunjuk benda dan menyebutkan namanya.',
                'rekomendasi2' => 'Gunakan lagu anak-anak dengan lirik sederhana.',
                'rekomendasi3' => 'Hindari penggunaan gadget atau TV sebagai pengganti interaksi langsung.',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 1,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'MRI kepala untuk evaluasi struktur otak',
                'rekomendasi2' => 'Stimulasi sensorik dengan terapis okupasi',
                'rekomendasi3' => 'Susu formula fortifikasi dengan DHA tinggi',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 2,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Konsultasi dokter gizi untuk evaluasi nutrisi',
                'rekomendasi2' => 'Susu formula tinggi kalori atau suplemen',
                'rekomendasi3' => 'Pantau pertumbuhan berat badan setiap minggu',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 3,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan hormon pertumbuhan dan tiroid',
                'rekomendasi2' => 'Fisioterapi untuk memperkuat otot kaki',
                'rekomendasi3' => 'Susu fortifikasi dengan ekstra kalsium dan vitamin D',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 4,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Terapi fisik intensif untuk memperkuat otot kaki',
                'rekomendasi2' => 'Stimulasi motorik dengan pijatan lembut',
                'rekomendasi3' => 'Konsultasi dokter untuk menyingkirkan gangguan neurologis',
            ],
            [
                'usia_id' => 5,
                'indikator_id' => 5,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan pendengaran (OAE/ABR)',
                'rekomendasi2' => 'Terapis wicara untuk stimulasi intensif',
                'rekomendasi3' => 'Gunakan bahasa isyarat sederhana (misal: melambai, tepuk tangan)',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 1,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Berikan puzzle sederhana (2-3 keping) dan mainan sortir bentuk.',
                'rekomendasi2' => 'Bermain dengan berbagai tekstur (pasir kinetik, playdough)',
                'rekomendasi3' => 'Ukur lingkar kepala setiap 3 bulan.',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 2,
                'kategori' => 'Normal',
                'rekomendasi1' => '3x makanan utama + 2x snack sehat',
                'rekomendasi2' => 'Perkenalkan berbagai rasa dan tekstur',
                'rekomendasi3' => 'Pantau kenaikan berat badan setiap bulan.',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 3,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Bermain bola, mendorong mainan troli',
                'rekomendasi2' => '2 gelas susu/hari + sinar matahari pagi',
                'rekomendasi3' => 'Berikan makanan padat yang kaya nutrisi.',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 4,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Berjalan di atas garis lurus di lantai',
                'rekomendasi2' => 'Bermain menyusun balok (4-6 tingkat)',
                'rekomendasi3' => 'Melempar dan menangkap bola besar',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 5,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Menyebut nama benda yang ditunjuk',
                'rekomendasi2' => 'Buku dengan gambar dan kalimat pendek',
                'rekomendasi3' => 'Beri waktu 5 detik untuk anak merespons',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 1,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Tingkatkan asupan omega-3 (ikan salmon 2x/minggu, alpukat)',
                'rekomendasi2' => 'Permainan yang melibatkan kedua tangan (memindahkan kacang dari wadah)',
                'rekomendasi3' => 'Konsultasi dokter anak untuk pemeriksaan perkembangan',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 2,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Keju parut, alpukat, minyak zaitun pada makanan',
                'rekomendasi2' => 'Makan setiap 3-4 jam dalam porsi kecil',
                'rekomendasi3' => 'Zink dan vitamin A sesuai anjuran dokter',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 3,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Naik-turun tangga dengan pegangan',
                'rekomendasi2' => 'Telur setiap hari + daging 3x/minggu',
                'rekomendasi3' => 'Berikan Vitamin D 400 IU/hari',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 4,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Tarik-mainan dengan tali untuk melatih berjalan',
                'rekomendasi2' => 'Menendang bola perlahan',
                'rekomendasi3' => 'Konsultasi fisioterapis jika belum bisa jalan di 18 bulan',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 5,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Ucapkan kata dengan benar ("Mau susu?" bukan "Cucu?")',
                'rekomendasi2' => 'Bermain Kartu bergambar dengan nama benda',
                'rekomendasi3' => 'Hindari Mengkritik pelafalan anak',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 1,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan neurologis lengkap (MRI/CT scan)',
                'rekomendasi2' => 'Terapis okupasi untuk stimulasi sensorik intensif',
                'rekomendasi3' => 'Susu formula fortifikasi dengan DHA tinggi',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 2,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Konsultasi dokter gizi untuk evaluasi nutrisi',
                'rekomendasi2' => 'Susu formula tinggi kalori atau suplemen',
                'rekomendasi3' => 'Pantau pertumbuhan berat badan setiap minggu',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 3,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan hormon pertumbuhan dan tiroid',
                'rekomendasi2' => 'Fisioterapi untuk memperkuat otot kaki',
                'rekomendasi3' => 'Susu fortifikasi dengan ekstra kalsium dan vitamin D',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 4,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Terapi fisik intensif untuk memperkuat otot kaki',
                'rekomendasi2' => 'Stimulasi motorik dengan pijatan lembut',
                'rekomendasi3' => 'Konsultasi dokter untuk menyingkirkan gangguan neurologis',
            ],
            [
                'usia_id' => 6,
                'indikator_id' => 5,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan pendengaran (OAE/ABR)',
                'rekomendasi2' => 'Terapis wicara untuk stimulasi intensif',
                'rekomendasi3' => 'Gunakan bahasa isyarat sederhana (misal: melambai, tepuk tangan)',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 1,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Mainan konstruksi (lego, balok) dengan 20-50 keping',
                'rekomendasi2' => 'Bermain pasir, air, atau biji-bijian dengan pengawasan',
                'rekomendasi3' => 'Ukur setiap 6 bulan, pertumbuhan normal ±1 cm/tahun',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 2,
                'kategori' => 'Normal',
                'rekomendasi1' => '3x makanan utama + 2x snack sehat',
                'rekomendasi2' => 'Perkenalkan berbagai rasa dan tekstur',
                'rekomendasi3' => 'Pantau kenaikan berat badan setiap bulan.',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 3,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Bermain bola, mendorong mainan troli',
                'rekomendasi2' => '2 gelas susu/hari + sinar matahari pagi',
                'rekomendasi3' => 'Berikan makanan padat yang kaya nutrisi.',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 4,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Melempar/menangkap bola dengan 2 tangan',
                'rekomendasi2' => 'Bermain playdough untuk kekuatan jari',
                'rekomendasi3' => 'Berjalan di atas balok keseimbangan',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 5,
                'kategori' => 'Normal',
                'rekomendasi1' => 'Bercerita tentang kegiatan hari ini',
                'rekomendasi2' => 'Bermain peran (dokter-pasien, penjual-pembeli)',
                'rekomendasi3' => 'Mengenal konsep waktu (besok, kemarin)',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 1,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Bermain Puzzle 10-20 keping, permainan memori gambar',
                'rekomendasi2' => 'Berikan Ikan berlemak (tuna, sarden) 3x/minggu + kacang almond',
                'rekomendasi3' => 'Tes perkembangan kognitif di PAUD/posyandu',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 2,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Tambahkan 1 sdm minyak zaitun ke makanan',
                'rekomendasi2' => 'Makan setiap 3-4 jam dalam porsi kecil',
                'rekomendasi3' => 'Zink dan vitamin A sesuai anjuran dokter',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 3,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Naik-turun tangga dengan pegangan',
                'rekomendasi2' => 'Telur setiap hari + daging 3x/minggu',
                'rekomendasi3' => 'Berikan Vitamin D 400 IU/hari',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 4,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Latihan memegang pensil tripod grip',
                'rekomendasi2' => 'Menggambar garis vertikal/horizontal',
                'rekomendasi3' => 'Berjalan di atas balok keseimbangan',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 5,
                'kategori' => 'Risiko Sedang',
                'rekomendasi1' => 'Modeling kalimat benar ("Ibu masak sayur" bukan "Sayur dimasak Ibu")',
                'rekomendasi2' => 'Permainan menyusun kartu kata menjadi kalimat',
                'rekomendasi3' => 'Ajak bicara tentang gambar di majalah atau buku anak',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 1,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Program stimulasi intensif dengan psikolog anak',
                'rekomendasi2' => 'Berikan Susu fortifikasi + makanan tinggi DHA/EPA',
                'rekomendasi3' => 'CT Scan kepala + konsultasi neurologis',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 2,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Konsultasi dokter gizi untuk evaluasi nutrisi',
                'rekomendasi2' => 'Susu formula tinggi kalori atau suplemen',
                'rekomendasi3' => 'Pantau pertumbuhan berat badan setiap minggu',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 3,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Pemeriksaan fungsi tiroid dan pencernaan',
                'rekomendasi2' => 'Fisioterapi untuk memperkuat otot kaki',
                'rekomendasi3' => 'Susu formula tinggi kalori (1.5-2 kal/ml)',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 4,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Terapi fisik intensif untuk memperkuat otot kaki',
                'rekomendasi2' => 'Tes hormon pertumbuhan dan kromosom',
                'rekomendasi3' => 'Makanan tinggi arginin (daging merah, kacang)',
            ],
            [
                'usia_id' => 7,
                'indikator_id' => 5,
                'kategori' => 'Risiko Berat',
                'rekomendasi1' => 'Bermaiin Kartu bergambar untuk kebutuhan dasar',
                'rekomendasi2' => 'Terapis wicara untuk stimulasi intensif',
                'rekomendasi3' => 'Mengurutkan benda berdasarkan ukuran/warna',
            ],


        ];

        foreach ($rekomendasi as $key => $value) {
            Rekomendasi::create($value);
        }
    }
}
